site_name: Python Geocoder API
theme: readthedocs
Authors: Denis Carriere
Date: February 28, 2015
repo_url: https://github.com/DenisCarriere/geocoder
base_url: http://geocoder.readthedocs.org
markdown_extensions: ['tables', 'toc', 'meta', 'fenced_code']

pages:
# Home Page
# =========
- ['index.md', 'Home']

# User Guide
# ==========
- ['Quickstart.md', 'User Guide', 'Quickstart']

# Features
# ========
- ['features/GeoJSON.md', 'Features', 'GeoJSON']
- ['features/OpenStreetMap.md', 'Features', 'OpenStreetMap']
- ['features/Command Line Interface.md', 'Features', 'Command Line Interface']
- ['features/Confidence Score.md', 'Features', 'Confidence Score']
- ['features/Well-Known Text.md', 'Features', 'Well-Known Text']

# Providers
# =========
- ['providers/W3W.md', 'Providers', 'what3words']
- ['providers/Baidu.md', 'Providers', 'Baidu']
- ['providers/HERE.md', 'Providers', 'HERE']
- ['providers/ArcGIS.md', 'Providers', 'ArcGIS']
- ['providers/Bing.md', 'Providers', 'Bing']
- ['providers/CanadaPost.md', 'Providers', 'CanadaPost']
- ['providers/FreeGeoIP.md', 'Providers', 'FreeGeoIP']
- ['providers/Geocoder-ca.md', 'Providers', 'Geocoder.ca']
- ['providers/GeoNames.md', 'Providers', 'GeoNames']
- ['providers/Google.md', 'Providers', 'Google']
- ['providers/MapQuest.md', 'Providers', 'MapQuest']
- ['providers/MaxMind.md', 'Providers', 'MaxMind']
- ['providers/OpenStreetMap.md', 'Providers', 'OpenStreetMap']
- ['providers/GeoOttawa.md', 'Providers', 'GeoOttawa']
- ['providers/TomTom.md', 'Providers', 'TomTom']
- ['providers/Yahoo.md', 'Providers', 'Yahoo']